apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fraudguard-alert-worker-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: fraudguard-alert-worker
  namespaceSelector:
    matchNames:
      - fraudguard
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
