prometheus:
  url: http://monitoring-kube-prometheus-prometheus.monitoring.svc
  port: 9090

rules:
  default: false

  custom:
    - seriesQuery: 'fraud_latency_p95{namespace!="",pod!=""}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: "^fraud_latency_p95$"
        as: "fraud_latency_p95"
      metricsQuery: 'fraud_latency_p95{<<.LabelMatchers>>}'
