apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fraudguard-fastapi-hpa
  namespace: fraudguard
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fraudguard-fastapi

  # ðŸ”’ SAFE DEFAULTS (no sudden scaling)
  minReplicas: 1
  maxReplicas: 10

  metrics:
    - type: External
      external:
        metric:
          name: fraud_latency_p95
        target:
          type: Value
          value: "200m"   # 200ms
