apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fraudguard-fastapi-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: fraudguard-fastapi
  namespaceSelector:
    matchNames:
      - fraudguard
  endpoints:
    - port: http
      path: /metrics
      interval: 10s