apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: fraudguard-v2
  namespace: fraudguard
  labels:
    app: fraudguard
    version: v2
  annotations:
    seldon.io/no-engine: "true"   # âœ… IMPORTANT
spec:
  protocol: seldon
  predictors:
    - name: default
      replicas: 1
      graph:
        name: classifier
        type: MODEL
        implementation: CUSTOM
        modelUri: dummy
      componentSpecs:
        - spec:
            containers:
              - name: classifier
                image: 199964507152.dkr.ecr.us-east-1.amazonaws.com/fraudguard-model:v2
                imagePullPolicy: Always
                env:
                  - name: MODEL_VERSION
                    value: "v2"
                ports:
                  - containerPort: 9000
